language: ruby
rvm:
  - 2.2.3
  - rbx-2
  - ruby-head
before_install:
  - gem update --system
  - gem install bundler -v 1.10.6
install: 'bundle'
script: 'rake'
notifications:
    email:
        - pedro.carrico@gmail.com
